"$schema" = 'https://starship.rs/config-schema.json'

[character]
format = '[└](blue)[$symbol]($style) '
success_symbol = '[|>](green)'
error_symbol = '[|>](red)'
[directory]
format = '[┌](blue)[\[$path\]]($style)[$read_only]($read_only_style) '
